apiVersion: databricks.org/v1alpha1
kind: FHNDataBricksClaim
metadata:
  name: xp-fhn-databricks-poc-3 
  namespace: crossplane-system
spec:
  parameters:
    virtualNetworkId: vnet-id 
    resourceGroupName: rg-crossplane-poc-3
    mngedResourceGroupName: rg-databricks-poc-3
    compositionRevision: v1.2
  compositionSelector:
    matchLabels:
      provider: databricks-crossplane 
  compositionRevisionSelector:
    matchLabels:
      revision: v1.2
